// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "path";
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Default: store the SQLite file relative to the project root.
// On Railway (or any Node server), this resolves to <cwd>/prisma/dev.db.
// Override by setting DATABASE_URL in the Railway environment variables dashboard.
const DATABASE_URL =
  process.env["DATABASE_URL"] ??
  `file:${path.join(process.cwd(), "prisma", "dev.db")}`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: DATABASE_URL,
  },
});
